<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Chinmays-MacBook-Pro.local" failures="1" tests="17" name="TutorialoneTestNg.tutorialTestng" time="0.027" errors="0" timestamp="10 Jul 2018 05:55:22 GMT" skipped="2">
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="Testqwe" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="Test35" time="0.002"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="Test2" time="0.002">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at TutorialoneTestNg.tutorialTestng.Test2(tutorialTestng.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="Test1" time="0.011"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="Test3" time="0.000">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.002"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestF" time="0.001"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestG" time="0.000"/>
  <testcase classname="TutorialoneTestNg.tutorialTestng" name="TestE">
    <skipped/>
  </testcase> <!-- TestE -->
</testsuite> <!-- TutorialoneTestNg.tutorialTestng -->
